### ISSUE TITLE
build failure on OS X 10.10.5

### ISSUE THREAD

**Issue by pavoljuhas** [macvim-dev/macvim#741]
I am getting the following build error with recent macvim:

```
In file included from .../src/MacVim/MMAppController.m:42:
.../src/macvim/src/MacVim/MMVimController.h:22:7: error: 
      cannot find protocol declaration for 'NSTouchBarDelegate'; did you mean
      'NSToolbarDelegate'?
    , NSTouchBarDelegate
      ^~~~~~~~~~~~~~~~~~
      NSToolbarDelegate
```

This seems to be introduced in 515ef9f6 as detailed in https://github.com/macvim-dev/macvim/commit/515ef9f6#r30359521.

@ychin - please consider the following patch to fix that

```patch
diff --git a/src/MacVim/MacVim.h b/src/MacVim/MacVim.h
index 904acf7..feac200 100644
--- a/src/MacVim/MacVim.h
+++ b/src/MacVim/MacVim.h
@@ -29,6 +29,9 @@
 #ifndef MAC_OS_X_VERSION_10_12
 # define MAC_OS_X_VERSION_10_12 101200
 #endif
+#ifndef MAC_OS_X_VERSION_10_12_2
+# define MAC_OS_X_VERSION_10_12_2 101202
+#endif
 
 #ifndef NSAppKitVersionNumber10_10
 # define NSAppKitVersionNumber10_10 1343
```

**Comment by ychin** [comment]
I think a better patch is to define as “IS_TOUCHBAR_SUPPORTED” macro and take into account cases where 12.2 isnt defined at all, instead of patching in the MAX_OS_X_VERSION_10_2_2

I can submit a PR

**Comment by ychin** [comment]
Actually seems like #736 already fixes this but it hasn’t been merged yet.

**Comment by jpetrie** [comment]
I merged it.
